mysql:
    host: 127.0.0.1
    port: 3306
    db: gvb_db
    user: root
    password: dhxdl666
    config: "charset=utf8mb4&parseTime=True&loc=Local"
    log_level: dev
logger:
    level: info
    prefix: '[gvb]'
    director: log
    show_line: true
    log_in_console: true
system:
    host: 0.0.0.0
    port: 8080
    env: release
site_info:
    created_at: "2023-04-30"
    bei_an: qwerqwer
    title: dhxdlqwer
    email: 444346216@qq.com
    name: dhxdlqwer
qq:
    app_id: xx
    key: dhxdl
    redirect: http://xx.xx.com/login?flag=qq
qi_niu:
    enable: true
    access_key: "KtMX80Fc8jWJi47BS7JoFT8rOgeG1HmwPfOMkNvI"
    secret_key: "I7ue_wz6dFur1AExPD_oMsm1VGT0LyteE6KSX6ni"
    bucket: "dhxdl666"
    cdn: "ru2pmj6pz.hd-bkt.clouddn.com/"
    zone: "z0"
    prefix: "gvb"
    size: 5
email:
    host: smtp.qq.com
    port: 465
    user: 444346216@qq.com
    password: fprznfdwyvkicbbe
    default_from_email: dhxdl
    use_ssl: true
    user_tls: false
jwy:
    secret: qwer
    expires: 2
    issuer: "qwer"
upload:
    size: 2
    path: uploads/file
redis:
    port: 6379
    ip: "127.0.0.1"
    password: ""
    poolSize: 100



